spring.application.name=config-prod
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
spring.application.name=config-default
